id: IEFF24600
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.161649
last_modified: 2023-02-09 14:46:46.161772
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: en
bases:
  45E7:
    base_file: 45E7.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
